version: "3.8"

services:
  db:
    image: postgres:15
    container_name: swifturl-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "3306:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: swifturl_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

  # Optional GUI for Redis (optional but powerful)
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  db_data:
  redis_data:
