version: "3.8"

services:
  db:
    image: postgres:15
    container_name: swifturl-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "3306:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
